### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by shenglunch** [JinhwiPark/DepthPrompting#1]
Which is the weight of MiDas/KBR in google drive?

**Comment by shenglunch** [comment]
I want to know the backbone and training data for each weight, and which weight is using MiDas/KBR as the backbone.

**Comment by JinhwiPark** [comment]
Sorry for the wait. Currently, we provide the code, experimental protocol, and weight files corresponding to tables 1 and 2 of the paper. The pretrained weights currently uploaded are those for the model using Depthformer as the backbone. We would like to inform you that KBR MiDaS corresponds to the experiments in tables 3 and 4.

We are currently working on expanding to various depth foundation models (UniDepth, Marigold, DepthAnything, etc), and the weights for these models will be provided on this GitHub or in a new repository. Thank you for your interest, and if you have any questions, feel free to let us know at any time.
