### ISSUE TITLE
Pretrained renet models

### ISSUE THREAD

**Issue by EricYang3721** [JinhwiPark/DepthPrompting#2]
Hello @JinhwiPark,

Thanks for releasing the code. When I run the code it needs to load the pretained ResNet models as
`model_path = {
    'resnet18': 'pretrained/COMMON/resnet18.pth',
    'resnet34': 'pretrained/COMMON/resnet34.pth'
}
`
I didn't find these models in the url of your pre-trained weights. Could you help to release those or point us to the place to download those models, please?

Thank you very much!

**Comment by EricYang3721** [comment]
I wasn't able to reproduce the NYUv2 performance with downloaded models. Could you help to point out me where I got wrong, please?
1. Without using resnet model
```
python test_multiDataLoader.py --data_name NYU --dir_data /home/nrasrtf/src/src/DepthPrompting/data/nyudepth_hdf5  --gpus 0,1,2,3 --model_name depth_prompt_main --pretrain /home/nrasrtf/src/src/DepthPrompting/pretrained_weights/Depthprompting_depthformer_kitti.tar --prop_kernel 9 --conf_prop --prop_time 18 --patch_height 240 --patch_width 320 --nyu_val_samples 500,200,100,5,1 --init_scailing   --no_res_pre
```
Got following results
```
Test for various Sampels/Lidars: [500, 200, 100, 5, 1]
0.3117/0.2065 0.3416/0.2289 0.3839/0.2619 4.4319/4.1520 4.8406/4.6754
```
2. Downloaded resent base model from pytorch official website https://pytorch.org/vision/0.8/_modules/torchvision/models/resnet.html, and run following
```
python test_multiDataLoader.py --data_name NYU --dir_data /home/nrasrtf/src/src/DepthPrompting/data/nyudepth_hdf5  --gpus 0,1,2,3 --model_name depth_prompt_main --pretrain /home/nrasrtf/src/src/DepthPrompting/pretrained/OURS/Depthprompting_depthformer_kitti.tar --prop_kernel 9 --conf_prop --prop_time 18 --patch_height 240 --patch_width 320 --nyu_val_samples 500 --init_scailing
```
The model `Depthprompting_depthformer_kitti.tar` is from the official URL provided, didn't do any fine tuning or training.

**Comment by ZhangWeihao3014** [comment]
Like this?

**Comment by ZhangWeihao3014** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/COMMON/resnet34.pth'
 
Like this? The same problem.

**Comment by JinhwiPark** [comment]
Hello, @EricYang3721 

I apologize for the delay. The pre-trained ResNet models you need can be downloaded from the following links:

https://drive.google.com/drive/folders/1bJpi3X_bB2-pgZ1MhSNdWRNC8k3qj4OS?usp=drive_link

If you have any further questions, feel free to ask anytime.

Thank you!
